services:
    app_accounting.dbal.schema_filter:
        class: Doctrine\Bundle\DoctrineBundle\Dbal\RegexSchemaAssetFilter
        arguments: [ '#^(?!(accounting_accounts_number_seq)$).*#' ]
        tags:
            - { name: doctrine.dbal.schema_filter }
