parameters:
    env(JWT_SECRET_KEY): '%kernel.project_dir%/config/jwt/private.pem'
    env(JWT_PUBLIC_KEY): '%kernel.project_dir%/config/jwt/public.pem'

lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
