version: "3"

server:
    command: "php public/index.php"
    env:
        -   APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
    address: 0.0.0.0:8080
    pool:
        debug: false

        # In the peak load periods:
        # - for p75 server response time under 0.5s
        #         - client response time is under 3 seconds
        # - for median (p50) server response time under 0.3s
        #                  - client response time is under 1.8 seconds
        num_workers: 8
        max_queue_size: 48

        # Latency hard-limit
        allocate_timeout: 8s
        supervisor:
            max_worker_memory: 96
    ssl:
        address: 0.0.0.0:8083
        redirect: true # redirect from http to https
        cert: /app/config/tls/backend/certificate.crt
        key: /app/config/tls/backend/privateKey.key
    max_request_size: 64
    middleware: [ "static", "gzip" ]
    uploads:
        forbid: [ ".php", ".exe", ".bat" ]
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]

logs:
    mode: production
    channels:
        http:
            level: debug # Log all http requests, set to info to disable
        server:
            level: info # Everything written to worker stderr is logged
            mode: raw
        metrics:
            level: error

# Uncomment to use metrics integration
# rpc:
#   listen: tcp://127.0.0.1:6001

# Uncomment to use metrics integration
# metrics:
#   # prometheus client address (path /metrics added automatically)
#   address: "0.0.0.0:9180"
