version: "3"

server:
    command: "php public/index.php"
    env:
        -   APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
            VAR_DUMPER_FORMAT: server
            VAR_DUMPER_SERVER: dump_server:9912

http:
    address: 0.0.0.0:8080
    middleware: [ "static", "gzip" ]
    pool:
        debug: true
    ssl:
        address: 0.0.0.0:8083
        redirect: true
        cert: /app/config/tls/http/certificate.crt
        key: /app/config/tls/http/privateKey.key
    uploads:
        forbid: [ ".php", ".exe", ".bat" ]
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]

grpc:
    listen: "tcp://0.0.0.0:50051"
    tls: # Enable mTLS for gRPC by providing a certificate and private key.
        cert: /app/config/tls/grpc/server/certificate.crt
        key: /app/config/tls/grpc/server/privateKey.key
        client_auth_type: require_and_verify_client_cert # full mTLS
        root_ca: /app/config/tls/grpc/client/certificate.crt # trusted client certificates
    proto:
        - "src/Support/Contracts/*/*/*/*.proto"
        - "src/Support/Contracts/*/*/*.proto"
        - "src/Support/Contracts/*/*.proto"

metrics:
    address: "0.0.0.0:2112"

temporal:
    address: "temporal:7233"
    activities:
        debug: true

# Used by rr reset command
# as well as metrics client
rpc:
    listen: tcp://127.0.0.1:6001

logs:
    mode: development
    channels:
        http:
            level: debug # Log all http requests, set to info to disable
        server:
            level: info # Everything written to worker stderr is logged
            mode: raw
        metrics:
            level: debug
