api_frontend_auth:
    resource: '../../Domain/**/{*FrontendAction.php}'
    type: attribute
    prefix: /api/employee-portal/auth
    host: '%api_host%'
    schemes: '%api_scheme%'

when@dev: &api_doc
    app.employee_portal_auth.swagger_ui:
        path: /api/employee-portal/auth/doc.html
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: employee_portal_auth }

    app.employee_portal_auth.swagger:
        path: /api/employee-portal/auth/doc.json
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger, area: employee_portal_auth }

when@stage: *api_doc
