api_frontend_auth:
    resource: '../../Domain/**/{*FrontendAction.php}'
    type: attribute
    prefix: /api/employee-portal/auth
    host: '%api_host%'
    schemes: '%api_scheme%'

when@dev:
    app.employee_portal_auth.redocly: &api_redocly
        path: /api/employee-portal/auth/doc.html
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.redocly, area: employee_portal_auth }

    app.employee_portal_auth.swagger: &api_json
        path: /api/employee-portal/auth/doc.json
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger, area: employee_portal_auth }

when@stage:
    app.employee_portal_auth.redocly: *api_redocly
    app.employee_portal_auth.swagger: *api_json
