<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Support/Contracts/Playground/HelloWorld/hello-world.proto

namespace GPBMetadata\Support\Contracts\Playground\HelloWorld;

class HelloWorld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xC9\x02\x0A9Support/Contracts/Playground/HelloWorld/hello-world.proto\x120App.Support.Contracts.Playground.HelloWorld.GRPC\"+\x0A\x04Name\x12\x11\x0A\x09firstName\x18\x01 \x01(\x09\x12\x10\x0A\x08lastName\x18\x02 \x01(\x09\"\x19\x0A\x05Hello\x12\x10\x0A\x08response\x18\x01 \x01(\x092\x89\x01\x0A\x0AHelloWorld\x12{\x0A\x08sayHello\x126.App.Support.Contracts.Playground.HelloWorld.GRPC.Name\x1A7.App.Support.Contracts.Playground.HelloWorld.GRPC.Hellob\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

