services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Support\Logging\:
        resource: '../../../**/{*LogProcessor.php}'

    Monolog\Processor\UidProcessor:
        tags:
            - { name: monolog.processor }

    Symfony\Bridge\Monolog\Processor\WebProcessor:
        tags:
            - { name: monolog.processor }

    Monolog\Processor\MemoryUsageProcessor:
        tags:
            - { name: monolog.processor }

    Monolog\Processor\MemoryPeakUsageProcessor:
        tags:
            - { name: monolog.processor }
