<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: Support/Contracts/Playground/HelloWorld/hello-world.proto

namespace App\Support\Contracts\Playground\HelloWorld\GRPC;

use Spiral\RoadRunner\GRPC;

interface HelloWorldInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "App.Support.Contracts.Playground.HelloWorld.GRPC.HelloWorld";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Name $in
    * @return Hello
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function sayHello(GRPC\ContextInterface $ctx, Name $in): Hello;
}
