<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Support/Contracts/Playground/HelloWorld/hello-world.proto

namespace App\Support\Contracts\Playground\HelloWorld\GRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>App.Support.Contracts.Playground.HelloWorld.GRPC.Hello</code>
 */
class Hello extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string response = 1;</code>
     */
    protected $response = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $response
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Support\Contracts\Playground\HelloWorld\HelloWorld::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string response = 1;</code>
     * @return string
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>string response = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkString($var, True);
        $this->response = $var;

        return $this;
    }

}

