services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\FrontPortal\AuthBundle\Domain\:
        resource: '../../Domain/{**/*Action.php,**/*Handler.php}'

imports:
    - { resource: '../../Domain/**/config/services.yaml' }
