services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\FrontPortal\AuthBundle\:
        resource: '../../{**/*Action.php,**/*Handler.php}'

imports:
    - { resource: '../../Scenarios/**/config/services.yaml' }
