framework:
    messenger:
        buses:
            api.bus:
                default_middleware: false
                middleware:
                    -   add_bus_name_stamp_middleware: [ api.bus ]
                    - phd_exception_handler
                    - app_message_forwarder

            api.exception.bus:
                default_middleware: false
                middleware:
                    - phd_exception_rethrow_unhandled
                    - phd_exception_chaining
                    - phd_exception_result_filter
                    -   handle_message:
                            - true
