services:
    centrifugo:
        image: centrifugo/centrifugo:v6.2
        command: [ "centrifugo", "--config=/centrifugo/config.json" ]
        volumes:
            - "./Bundle/Resources/config/centrifugo.json:/centrifugo/config.json"
            - "./Bundle/Resources/prototype:/centrifugo/prototype"
        ports:
            - "127.0.0.1:8008:8000"
            - "127.0.0.1:3003:3000"
