doctrine:
    orm:
        mappings:
            AppBlogBundle:
                type: attribute
                dir: '%kernel.project_dir%/src/EmployeePortal/Blog'
                is_bundle: false
                prefix: App\EmployeePortal\Blog
