doctrine:
    dbal:
        default_connection: default
        dbname: '%env(DATABASE_NAME)%'
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        driver: pdo_pgsql
        server_version: '%env(DATABASE_VERSION)%'
        charset: UTF8
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings: { }
        controller_resolver:
            auto_mapping: false
            enabled: false
        # metadata_cache_driver option must not be set to allow
        # Doctrine Bundle to use PhpArrayAdapter that leverage opcache's shared memory, and adds warm-up logic
        query_cache_driver:
            type: pool
            pool: doctrine.query_cache_pool

#        result_cache_driver:
#            type: pool
#            pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.query_cache_pool:
                adapter: cache.adapter.system

            doctrine.result_cache_pool:
                adapter: cache.adapter.redis

# make sure metadata cache clears on the new migration
stfalcon_studio_doctrine_redis_cache:
    cache_pools: [ 'cache.doctrine.orm.default.metadata' ]

when@test: &local_config
    doctrine:
        dbal:
            logging: true
            profiling: true

when@dev: *local_config
