services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Playground\:
        resource: '../../../**/{*Action.php,*ConsoleCommand.php,*Handler.php,*Repository.php}'

imports:
    - { resource: '../../../**/config/services.yaml' }
