services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Playground\:
        resource: '../../../**/{*ApiPoint.php,*ConsoleCommand.php,*Provider.php,*Service.php,*Handler.php,*Repository.php,*Workflow.php,*Activity.php,*Formatter.php}'
