playground_routes:
    resource: '@AppPlaygroundBundle/Resources/config/routes.yaml'

auth_routes:
    resource: '@AppAuthBundle/Resources/config/routes.yaml'

#accounting_routes:
#    resource: '@AppAccountingBundle/Resources/config/routes.yaml'

voucher_routes:
    resource: '@AppVoucherBundle/Resources/config/routes.yaml'

blog_routes:
    resource: '@AppBlogBundle/Resources/config/routes.yaml'

web_socket_routes:
    resource: '@AppWebSocketBundle/Resources/config/routes.yaml'
