framework:
    messenger:
        default_bus: default.bus

        buses:
            # default bus should not be used
            default.bus:
                default_middleware: false
                middleware:
                    - handle_message

            command.bus:
                default_middleware: false
                middleware:
                    - app_unwrap_exception
                    - phd_exceptional_validation
                    - doctrine_transaction
                    - handle_message

            query.bus:
                default_middleware: false
                middleware:
                    - app_unwrap_exception
                    - phd_exceptional_validation
                    - handle_message

            event.bus:
                default_middleware: false
                middleware:
                    -   handle_message:
                            - true
