framework:
    messenger:
        buses:
            ws.event.bus:
                default_middleware: false
                middleware:
                    - dispatch_after_current_bus
                    - handle_message
