doctrine:
    orm:
        mappings:
            AppAuthBundle:
                type: attribute
                dir: '%kernel.project_dir%/src/EmployeePortal/Authentication'
                is_bundle: false
                prefix: App\EmployeePortal\Authentication
