api_frontend_auth:
    resource: '../../../**/{*FrontendApiPoint.php}'
    type: attribute
    prefix: /api/example-project/auth
    host: '%api_host%'
    schemes: '%api_scheme%'

api_example_project_auth_token_refresh:
    path: /api/example-project/auth/token/refresh
    methods: POST
    host: '%api_host%'
    schemes: '%api_scheme%'

when@dev:
    api_doc.example_project_auth.redocly: &api_doc_redocly
        path: /api/example-project/auth/doc.html
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.redocly, area: example_project_auth }

    api_doc.example_project_auth.swagger: &api_doc_json
        path: /api/example-project/auth/doc.json
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger, area: example_project_auth }

when@stage:
    api_doc.example_project_auth.redocly: *api_doc_redocly
    api_doc.example_project_auth.swagger: *api_doc_json
