services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\EmployeePortal\Authentication\:
        resource: '../../../**/{*ApiPoint.php,*ConsoleCommand.php,*Service.php,*Middleware.php,*Provider.php,*Fixture.php,*Repository.php}'
