parameters:
    env(TEMPORAL_ADDRESS): 'host.docker.internal:7233'
    env(RR_RPC): 'tcp://127.0.0.1:6001'

temporal:
    defaultClient: default
    pool:
        dataConverter: temporal.data_converter
        roadrunnerRPC: '%env(RR_RPC)%'

    workers:
        default:
            taskQueue: default
            exceptionInterceptor: temporal.exception_interceptor
            finalizers:
                - temporal.doctrine_ping_connection_default.finalizer
                - temporal.doctrine_clear_entity_manager.finalizer
            interceptors:
                - temporal.doctrine_ping_connection_default_activity_inbound.interceptor

    clients:
        default:
            namespace: default
            address: '%env(TEMPORAL_ADDRESS)%'
            dataConverter: temporal.data_converter
            grpcContext:
                timeout:
                    value: 10
