api_frontend_blog:
    resource: '../../../../**/{*FrontendApiPoint.php}'
    type: attribute
    prefix: /api/example-project/blog
    host: '%api_host%'
    schemes: '%api_scheme%'

when@dev:
    api_doc.example_project_blog.redocly: &api_doc_redocly
        path: /api/example-project/blog/doc.html
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.redocly, area: example_project_blog }

    api_doc.example_project_blog.swagger: &api_doc_json
        path: /api/example-project/blog/doc.json
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger, area: example_project_blog }

when@stage:
    api_doc.example_project_blog.redocly: *api_doc_redocly
    api_doc.example_project_blog.swagger: *api_doc_json
