temporal:
    workers:
        trip_booking:
            taskQueue: trip_booking
            exceptionInterceptor: temporal.exception_interceptor
            finalizers:
                - temporal.doctrine_ping_connection_default.finalizer
                - temporal.doctrine_clear_entity_manager.finalizer
            interceptors:
                - temporal.doctrine_ping_connection_default_activity_inbound.interceptor
